create table if not exists ${AQTS_SCHEMA_NAME}.time_series_interpolation_types
(time_series_interpolation_types_id      bigint generated by default as identity (start with 1)
,json_data_id                            bigint
,start_time                              timestamp
,end_time                                timestamp
,interpolation_type                      text
,partition_number                        integer
,primary key (time_series_interpolation_types_id, partition_number)
)
partition by list (partition_number);
