create table if not exists ${AQTS_SCHEMA_NAME}.aq_comp_id_to_stat_cd
(aq_comp_id_to_stat_cd_id  bigint generated by default as identity (start with 1)
,computation_identifier                  character varying (200)
,stat_cd                                 character varying (5)
,primary key (aq_comp_id_to_stat_cd_id)
,constraint aq_comp_id_to_stat_cd_ak unique (computation_identifier)
)
