create table if not exists ${AQTS_SCHEMA_NAME}.time_series_header_info
(time_series_header_info_id              bigint generated by default as identity (start with 1)
,json_data_id                            bigint
,time_series_unique_id                   character varying (32)
,notes                                   jsonb
,summary                                 text
,num_points                              integer
,time_range_start                        timestamp
,time_range_end                          timestamp
,response_time                           timestamp
,response_version                        integer
,location_identifier                     text
,partition_number                        integer default extract( month from now() )
)
partition by list (partition_number);