create table if not exists ${AQTS_SCHEMA_NAME}.time_series_methods
(time_series_methods_id                  bigint generated by default as identity (start with 1)
,json_data_id                            bigint
,start_time                              timestamp
,end_time                                timestamp
,method_code                             text
,primary key (time_series_methods_id)
);
