create table if not exists ${AQTS_SCHEMA_NAME}.field_visit_header_info
(field_visit_header_info_id                bigint generated by default as identity (start with 1)
	,json_data_id                            bigint
	,field_visit_identifier                  text
	,location_identifier                     text
	,start_time                              timestamp
	,end_time                                timestamp
	,party                                   text
	,remarks                                 text
	,weather                                 text
	,is_valid                                text
	,completed_work                          jsonb
	,last_modified                           timestamp
	,partition_number                        integer default extract( month from now() )
)
partition by list (partition_number);