create table if not exists ${AQTS_SCHEMA_NAME}.time_series_gap_tolerances
(time_series_gap_tolerances_id           bigint generated by default as identity (start with 1)
,time_series_unique_id                   character varying (32)
,start_time                              timestamp
,end_time                                timestamp
,tolerance_in_minutes                    integer
,response_time                           timestamp
,response_version                        integer
,primary key (time_series_gap_tolerances_id)
,constraint time_series_gap_tolerances_ak unique (time_series_unique_id, start_time)
);
