create table if not exists ${AQTS_SCHEMA_NAME}.time_series_gap_tolerances
(time_series_gap_tolerances_id           bigint generated by default as identity (start with 1)
,json_data_id                            bigint
,start_time                              timestamp
,end_time                                timestamp
,tolerance_in_minutes                    integer
,partition_number                        integer default extract( month from now() )
)
partition by list (partition_number);
