create table if not exists ${AQTS_SCHEMA_NAME}.field_visit_readings
(field_visit_readings_id                bigint generated by default as identity (start with 1)
	,json_data_id                            bigint
	,parameter                               text
	,monitoring_method                       text
	,field_visit_value                       jsonb
	,unit                                    text
	,uncertainty                             jsonb
	,reading_type                            text
	,manufacturer                            text
	,model                                   text
	,serial_number                           text
	,field_visit_time                        timestamp
	,field_visit_comments                    text
	,publish                                 text
	,is_valid                                text
	,reference_point_unique_id               text
	,use_location_datum_as_reference         text
	,reading_qualifier                       text
	,reading_qualifiers                      jsonb
	,ground_water_measurement                jsonb
	,partition_number                        integer default extract( month from now() )
)
partition by list (partition_number);
