create table if not exists ${AQTS_SCHEMA_NAME}.field_visit_readings
(field_visit_readings_id                 bigint generated by default as identity (start with 1)
,json_data_id                            bigint
,field_visit_identifier                  text
,parameter                               text
,monitoring_method                       text
,field_visit_value                       text
,unit                                    text
,uncertainty                             text
,reading_type                            text
,manufacturer                            text
,model                                   text
,serial_number                           text
,field_visit_time                        timestamp
,field_visit_comments                    text
,publish                                 text
,is_valid                                text
,reference_point_unique_id               text
,use_location_datum_as_reference         text
,reading_qualifier                       text
,reading_qualifiers                      text
,ground_water_measurement                text
,partition_number                        integer
,primary key (field_visit_readings_id, partition_number)
)
partition by list (partition_number);
