create table if not exists ${AQTS_SCHEMA_NAME}.aq_to_nwis_parm
(aq_to_nwis_parm_id  bigint generated by default as identity (start with 1)
,parameter                               character varying (200)
,parm_cd                                 character varying (5)
,primary key (aq_to_nwis_parm_id)
,constraint aq_to_nwis_parm_ak unique (parameter)
)
