create table if not exists ${AQTS_SCHEMA_NAME}.time_series_qualifiers
(time_series_qualifiers_id               bigint generated by default as identity (start with 1)
,json_data_id                            bigint
,start_time                              timestamp
,end_time                                timestamp
,qualifier_user                          text
,identifier                              text
,date_applied_utc                        timestamp
,partition_number                        integer default extract( month from now() )
)
partition by list (partition_number);
