create table if not exists ${AQTS_SCHEMA_NAME}.time_series_grades
(time_series_grades_id                   bigint generated by default as identity (start with 1)
,time_series_unique_id                   character varying (32)
,start_time                              timestamp with time zone
,end_time                                timestamp with time zone
,grade_code                              text
,primary key (time_series_grades_id)
,constraint time_series_grades_ak unique (time_series_unique_id, start_time)
);
