create table if not exists ${AQTS_SCHEMA_NAME}.aq_to_nwis_method_code
(aq_to_nwis_method_code_id               bigint generated by default as identity (start with 1)
,aqts_monitoring_method                  character varying (200)
,nwis_method_description                 character varying (200)
,nwis_method_code                        character varying (1)
,primary key (aq_to_nwis_method_code_id)
,constraint aq_to_nwis_method_code_ak unique (aqts_monitoring_method)
)
