create table if not exists ${AQTS_SCHEMA_NAME}.time_series_points
(time_series_points_id                   bigint generated by default as identity (start with 1)
,json_data_id                            bigint
,time_step                               timestamp
,numeric_value                           decimal
,display_value                           text
,partition_number                        integer
,primary key (time_series_points_id, partition_number)
)
partition by list (partition_number);
