create table if not exists ${AQTS_SCHEMA_NAME}.time_series_points
(time_series_points_id                   bigint generated by default as identity (start with 1)
,json_data_id                            bigint
,time_step                               timestamp
,numeric_value                           decimal
,display_value                           text
,primary key (time_series_points_id)
,constraint time_series_points_ak unique (json_data_id, time_step)
);
